## **Encoding categorical data**


convert categorical variables into numbers

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#country , age and salary
data = [['India',np.nan,68000.0],
    ['France',43.0,45000.0],
 [np.nan,30.0, 54000.0],
 ['France' ,48.0, 65000.0],
 ['Germany' ,40.0, np. nan],
 ['India' ,35.0, 58000.0],
 ['Germany', np.nan ,53000.0],
 ['France' ,49.0, 79000.0],
 ['India', 50.0 ,88000.0],
 [np.nan ,37.0, np.nan]]

In [ ]:
df = pd.DataFrame(data)
df

0     1        2
0    India   NaN  68000.0
1   France  43.0  45000.0
2      NaN  30.0  54000.0
3   France  48.0  65000.0
4  Germany  40.0      NaN
5    India  35.0  58000.0
6  Germany   NaN  53000.0
7   France  49.0  79000.0
8    India  50.0  88000.0
9      NaN  37.0      NaN

In [ ]:
df[0]

0      India
1     France
2        NaN
3     France
4    Germany
5      India
6    Germany
7     France
8      India
9        NaN
Name: 0, dtype: object

In [ ]:
df[0].unique()

array(['India', 'France', nan, 'Germany'], dtype=object)

In [ ]:
#Replace method
df[0].replace({'India':0, 'France':1, 'NaN':2, 'Germany':3})

0    0.0
1    1.0
2    NaN
3    1.0
4    3.0
5    0.0
6    3.0
7    1.0
8    0.0
9    NaN
Name: 0, dtype: float64

In [ ]:
#Map method
df[0].map({'India':0, 'France':1, 'NaN':2, 'Germany':3})

0    0.0
1    1.0
2    NaN
3    1.0
4    3.0
5    0.0
6    3.0
7    1.0
8    0.0
9    NaN
Name: 0, dtype: float64

Sklearn preprocessing
# Label Encoder

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb = LabelEncoder()
lb.fit_transform(df[0])

array([2, 0, 3, 0, 1, 2, 1, 0, 2, 3])

In [ ]:
df[0].values

array(['India', 'France', nan, 'France', 'Germany', 'India', 'Germany',
       'France', 'India', nan], dtype=object)

In [ ]:
lb.classes_

array(['France', 'Germany', 'India', nan], dtype=object)

In [ ]:
g = pd.DataFrame({'gender':['male','female','female','male','male','female'],
             'cat':['A','A','A','B','C','C']})
g

gender cat
0    male   A
1  female   A
2  female   A
3    male   B
4    male   C
5  female   C

In [ ]:
lb.fit_transform(g.gender)

array([1, 0, 0, 1, 1, 0])

In [ ]:
lb.classes_

array(['female', 'male'], dtype=object)

In [ ]:
#Load datasets


In [ ]:
import seaborn as sns

In [ ]:
t = sns.load_dataset('titanic')
t

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [ ]:
t['sex']

0        male
1      female
2      female
3      female
4        male
        ...  
886      male
887    female
888    female
889      male
890      male
Name: sex, Length: 891, dtype: object

In [ ]:
lb.fit_transform(t['sex'])

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,

In [ ]:
new_data= [1,1,1,1,1,0,0,0,0,0,1,0,1,1,1,0,0,1,1,0,1]
new_data

[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1]

In [ ]:
lb.inverse_transform(new_data)

array(['male', 'male', 'male', 'male', 'male', 'female', 'female',
       'female', 'female', 'female', 'male', 'female', 'male', 'male',
       'male', 'female', 'female', 'male', 'male', 'female', 'male'],
      dtype=object)